apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v213papis-python 
  janus-idp.io/tekton: v213papis-python
  backstage.io/kubernetes-id: v213papis-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v213papis-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml