apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v213papis-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v213papis-python 
  name: v213papis-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v213papis-python 
